name: sequence_app
description: System: Reason MUST YOU - Sequence reality distortion app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.3
  provider: ^6.1.2
  vibration: ^1.8.4
  flutter_local_notifications: ^17.2.2
  audioplayers: ^6.1.0
  awesome_notifications: ^0.9.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/sound/glitch_pop.mp3
    - assets/images/icon.png
